project_id     = "my-day02-project"
region         = "us-central1"
ins_group_name = "webserver-igm"
name           = "http-lb"
lb_proxy_port  = "80"
lb_proxy_port_name = "http"
lb_hc_port     = "80"
lb_protocol    = "HTTP"
